<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="UseCases\Dapper\Commands\" />
    <Folder Include="UseCases\Dapper\Queries\" />
    <Folder Include="UseCases\EntityFramework\" />
    <Folder Include="Validators\" />
    <Folder Include="UseCases\EntityFramework\Commands\" />
    <Folder Include="UseCases\EntityFramework\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
  </ItemGroup>

</Project>
